version: 2
jobs:
  build:
    working_directory: /go/src/github.com/timehop/golog 
    environment:
      DOCKER_USER: timehopinfra
    docker:
      # Primary container image where all steps run.
      - image: timehop/circleci-2.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: 
          name: Running tests
          command: ginkgo -r --randomizeAllSpecs --skipMeasurements --cover --trace --race
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
